spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    druid:
      url: jdbc:mysql://mysqlServer:3306/u2ps?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
      username: mysqlUser
      password: mysqlPass
      initial-size: 1
      min-idle: 3
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 6
    host: redisServer
    port: 5070
    timeout: 1500
    password: redisPass
    jedis:
      pool:
        max-active: -1 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 10 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 2 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
logging:
  file:
    path: "./logs/"
    name: "./logs/u2ps.log"
  file.max-size: 100MB
u2ps:
  ps:
    port: 2251
  askNode:
    num: 30
    interval: 100
dubbo:
  application:
    name: u2ps-server
  protocol:
    name: dubbo #通信协议
    port: -1 #端口自增
  registry:
    address: nacos://nacosServer:8848 #nacos服务器地址
  scan:
    base-packages: cn.p00q.u2ps.service.impl #扫描服务包路径